/**
 * Circuit layout.
 *
 * The road is no longer invented. `./road.ts` is generated by
 * scripts/fit-circuit.mjs, which aligns the 3D model of the circuit to the
 * projected geodata in ./centreline.ts and then *measures* the road off the
 * model's own asphalt: the middle of the paved corridor, how far the asphalt
 * runs to either side, the surface height and the cross-slope, at 1024 samples
 * around the lap. This module turns those numbers into the same `Layout` the
 * rest of the game already consumed — arc length, signed curvature, an
 * orthonormal road frame per sample — so lap timing, the minimap, respawns and
 * the grid slot all sit on the asphalt the player can see.
 *
 * What changed when the model arrived: elevation, banking and width used to be
 * functions invented here (two harmonics of the lap for the elevation, a
 * curvature-proportional bank, a constant 14 m width). All three are now read
 * off the model. The cosmetic tunnels are gone too — the model has real ones.
 * Curvature analysis stayed, because nothing in the model labels its corners.
 *
 * World units are metres at true scale; one lap is ~5.4 km.
 */
import { Vector3 } from 'three'

import { ROAD, ROAD_LAP, ROAD_START, ROAD_STRIDE } from './road'

/** Number of samples around the lap. Fixed by the generated data. */
export const SAMPLES = ROAD.length / ROAD_STRIDE

/** La Monumental: the length of the window the curvature search looks for. */
export const MONUMENTAL_LENGTH = 550

const wrap = (i: number, n: number): number => ((i % n) + n) % n

/** Circular moving average. */
function smooth(values: number[], halfWindow: number): number[] {
  const n = values.length
  const out = new Array<number>(n)
  for (let i = 0; i < n; i++) {
    let sum = 0
    for (let j = -halfWindow; j <= halfWindow; j++) sum += values[wrap(i + j, n)]
    out[i] = sum / (2 * halfWindow + 1)
  }
  return out
}

export interface Sample {
  /** Middle of the paved corridor, elevation included. */
  p: Vector3
  /** Unit tangent (direction of travel). */
  t: Vector3
  /** Unit "driver's right", rotated by the cross-slope. */
  r: Vector3
  /** Unit road normal, rotated by the cross-slope. */
  u: Vector3
  /** Arc length from the start/finish line, metres. */
  s: number
  /** Signed curvature, 1/m. Positive turns right. */
  k: number
  /** Cross-slope, radians. */
  bank: number
  /** Metres from `p` to the left-hand edge of the asphalt. */
  edgeLeft: number
  /** Metres from `p` to the right-hand edge of the asphalt. */
  edgeRight: number
  /** Half the paved width, for anything that wants one number. */
  halfWidth: number
}

export interface Section {
  /** Inclusive sample index range (may wrap past the end of the lap). */
  from: number
  to: number
  /** Arc length range, metres. */
  sFrom: number
  sTo: number
  length: number
}

export type Pose = { position: [number, number, number]; rotation: [number, number, number] }

export interface Layout {
  samples: Sample[]
  /** Lap length of the measured road, metres. */
  lapLength: number
  /** Spacing between samples, metres. */
  ds: number
  /** The signature banked loop, found by curvature analysis. */
  monumental: Section & { radius: number; headingChange: number }
  /** Where the car is placed, a little before the line. */
  grid: Pose
  /** Sample index of the grid slot. */
  gridIndex: number
  /** Sample index of the start/finish line — the model's own start gantry. */
  startIndex: number
}

/** Vertex position at lateral offset `u` metres and height `h` above the road. */
export function pointAt(sample: Sample, u: number, h: number, target = new Vector3()): Vector3 {
  return target.copy(sample.p).addScaledVector(sample.r, u).addScaledVector(sample.u, h)
}

/** Yaw that points the car's nose up the road at this sample. */
export function yawAt(sample: Sample): number {
  return Math.atan2(sample.t.x, sample.t.z)
}

/** Index of the sample whose centreline is closest to a world point. */
export function nearestIndex(layout: Pick<Layout, 'samples'>, x: number, z: number): number {
  let best = 0
  let bestDistance = Infinity
  for (let i = 0; i < layout.samples.length; i++) {
    const p = layout.samples[i].p
    const d = (p.x - x) ** 2 + (p.z - z) ** 2
    if (d < bestDistance) {
      bestDistance = d
      best = i
    }
  }
  return best
}

/** A drivable pose on the centreline: hovering slightly, facing forward. */
export function poseAt(layout: Pick<Layout, 'samples'>, index: number, ride = 1.2): Pose {
  const sample = layout.samples[index]
  const p = pointAt(sample, 0, ride)
  return { position: [p.x, p.y, p.z], rotation: [0, yawAt(sample), 0] }
}

/** Wrapped arc-length difference in [-lap/2, lap/2]. */
export function arcDelta(a: number, b: number, lap: number): number {
  let d = a - b
  while (d > lap / 2) d -= lap
  while (d < -lap / 2) d += lap
  return d
}

function build(): Layout {
  const n = SAMPLES
  const ds = ROAD_LAP / n

  // The generated data starts where the projected centreline started; rotate it
  // so index 0 is the model's own start/finish gantry.
  const shift = wrap(ROAD_START, n)
  const at = (i: number, field: number) => ROAD[wrap(i + shift, n) * ROAD_STRIDE + field]

  const points: Vector3[] = []
  const edgeLeft: number[] = []
  const edgeRight: number[] = []
  const bank: number[] = []
  for (let i = 0; i < n; i++) {
    points.push(new Vector3(at(i, 0), at(i, 1), at(i, 2)))
    edgeLeft.push(at(i, 3))
    edgeRight.push(at(i, 4))
    bank.push(at(i, 5))
  }

  // --- signed curvature ----------------------------------------------------
  const rawK = new Array<number>(n)
  for (let i = 0; i < n; i++) {
    const a = points[wrap(i - 1, n)]
    const b = points[i]
    const c = points[wrap(i + 1, n)]
    const t1x = b.x - a.x
    const t1z = b.z - a.z
    const t2x = c.x - b.x
    const t2z = c.z - b.z
    const l1 = Math.hypot(t1x, t1z) || 1e-6
    const l2 = Math.hypot(t2x, t2z) || 1e-6
    const cross = (t1x * t2z - t1z * t2x) / (l1 * l2)
    const dot = (t1x * t2x + t1z * t2z) / (l1 * l2)
    rawK[i] = Math.atan2(cross, dot) / ((l1 + l2) / 2)
  }
  const k = smooth(rawK, 6)

  // --- find La Monumental: the longest sustained single-direction turn -----
  // Prefix sums over the signed curvature: the ~550 m window whose *signed*
  // mean curvature is largest in magnitude is by definition the section that
  // turns hardest and never changes direction.
  const windowSamples = Math.max(2, Math.round(MONUMENTAL_LENGTH / ds))
  const prefix = new Array<number>(n * 2 + 1)
  prefix[0] = 0
  for (let i = 0; i < n * 2; i++) prefix[i + 1] = prefix[i] + k[wrap(i, n)]
  let bestStart = 0
  let bestMean = 0
  for (let i = 0; i < n; i++) {
    const mean = (prefix[i + windowSamples] - prefix[i]) / windowSamples
    if (Math.abs(mean) > Math.abs(bestMean)) {
      bestMean = mean
      bestStart = i
    }
  }
  const monumental = {
    from: bestStart,
    to: wrap(bestStart + windowSamples, n),
    sFrom: bestStart * ds,
    sTo: (bestStart + windowSamples) * ds,
    length: windowSamples * ds,
    radius: Math.abs(1 / bestMean),
    headingChange: bestMean * windowSamples * ds,
  }

  // --- assemble the road frames -------------------------------------------
  const up = new Vector3(0, 1, 0)
  const samples: Sample[] = []
  for (let i = 0; i < n; i++) {
    const p = points[i]
    const t = new Vector3().subVectors(points[wrap(i + 1, n)], points[wrap(i - 1, n)]).normalize()
    // Road frame, not a Frenet frame: the road only rolls by its cross-slope.
    const r = new Vector3().crossVectors(t, up).normalize()
    const u = new Vector3().crossVectors(r, t).normalize()
    const phi = bank[i]
    const rBanked = new Vector3().addScaledVector(r, Math.cos(phi)).addScaledVector(u, -Math.sin(phi)).normalize()
    const uBanked = new Vector3().crossVectors(rBanked, t).normalize()
    samples.push({
      p,
      t,
      r: rBanked,
      u: uBanked,
      s: i * ds,
      k: k[i],
      bank: bank[i],
      edgeLeft: edgeLeft[i],
      edgeRight: edgeRight[i],
      halfWidth: (edgeLeft[i] + edgeRight[i]) / 2,
    })
  }

  // --- grid slot -----------------------------------------------------------
  // A few car lengths before the line, on the racing line, facing forward.
  const gridIndex = wrap(-Math.round(30 / ds), n)

  return {
    samples,
    lapLength: ROAD_LAP,
    ds,
    monumental,
    startIndex: 0,
    gridIndex,
    grid: poseAt({ samples }, gridIndex),
  }
}

let cached: Layout | null = null

export function getLayout(): Layout {
  if (!cached) cached = build()
  return cached
}
