/*
 * The player car: APEX FORMULA 2026's sculpted formula car.
 *
 * Model — assets/f1car-2026.glb from APEX FORMULA 2026, a project-authored
 * asset (generated by its tools/blender/build_car.py; see that repository's
 * ASSET_PROVENANCE.md — no third-party logos or likenesses).
 *   Copyright 2026 Avi Hacker, J.D.
 *   https://github.com/ahacker-1/apex-formula-2026
 *   Licensed under the Apache License, Version 2.0; see
 *   ../../../LICENSES/apex-formula-2026-Apache-2.0.txt.
 * The material finishing (carbon/tyre tone-down, per-car body colour) follows
 * the reference's car.js; the mesh is used as exported. This replaces the
 * previous CC-BY muscle car by Alexus16, which is no longer shipped.
 *
 * Structure, from the exporter: top-level nodes `body_root` and
 * `wheel_fl/fr/rl/rr`, +Z forward, Y up, floor at y = 0.03, wheel radius 0.34.
 * The wheels steer with rotation.y and spin with rotation.x, in that order
 * ('YXZ'), exactly as the reference's race loop writes them.
 *
 * This component is purely visual. The pose comes from the analytic controller
 * (src/vehicle/CarController) via Vehicle.tsx; here we only apply the visual
 * body attitude (dive / squat / roll), the brake glow, the boost rain light
 * and the crash audio.
 */
import type { PropsWithChildren } from 'react'
import { forwardRef, useEffect, useMemo, useRef } from 'react'
import { PositionalAudio, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import type { Group, Mesh, MeshStandardMaterial, Object3D, PositionalAudio as PositionalAudioImpl } from 'three'
import { Color, MeshPhysicalMaterial } from 'three'

import { getState, mutation, useStore } from '../../store'
import { getPlayer } from '../../vehicle/CarController'
import { DRACO_PATH } from '../../draco'
import { asset } from '../../assets'

const c = new Color()

/** Only the big silhouette parts cast shadows. */
const SHADOW_CASTERS = new Set([
  'chassis',
  'sidepods',
  'airbox',
  'shark_fin',
  'floor',
  'helmet',
  'halo',
  'front_wing_main',
  'front_wing_endplates',
  'rear_wing_main',
  'rear_wing_flap',
  'rear_wing_endplates',
  'tyre_fl',
  'tyre_fr',
  'tyre_rl',
  'tyre_rr',
])

const WHEEL_NAMES = ['wheel_fl', 'wheel_fr', 'wheel_rl', 'wheel_rr'] as const

interface CarParts {
  root: Group
  body: Object3D
  wheelObjects: Object3D[]
  bodyMaterial: MeshStandardMaterial | null
  brakeGlows: Object3D[]
  rainLight: Object3D | null
  glowMaterial: MeshStandardMaterial | null
}

/**
 * Clone the loaded template and bake each top-level node's world matrix, so
 * body_root / wheel_* can be re-parented into our own group — the same
 * flattening the reference's prepareTemplate does.
 */
function prepare(scene: Group): CarParts {
  const src = scene.clone(true)
  src.updateMatrixWorld(true)
  const root = src
  const body = src.getObjectByName('body_root') as Object3D
  const wheelObjects = WHEEL_NAMES.map((name) => src.getObjectByName(name) as Object3D)
  for (const o of [body, ...wheelObjects]) {
    if (!o) continue
    o.matrix.copy(o.matrixWorld)
    o.matrix.decompose(o.position, o.quaternion, o.scale)
    // steer (y) is applied before spin (x); keeps the axle horizontal
    o.rotation.order = 'YXZ'
  }

  let bodyMaterial: MeshStandardMaterial | null = null
  let glowMaterial: MeshStandardMaterial | null = null
  // Show-car paint, the three.js webgl_materials_car recipe (MIT): metallic
  // base under a hard clearcoat. Shared by every mesh that carries the
  // exported 'body' or 'accent' paint; tinted live with the picked colour.
  const paint = new MeshPhysicalMaterial({ metalness: 0.9, roughness: 0.4, clearcoat: 1.0, clearcoatRoughness: 0.03, envMapIntensity: 1 })
  paint.name = 'body'
  const accentPaint = new MeshPhysicalMaterial({ metalness: 0.9, roughness: 0.4, clearcoat: 1.0, clearcoatRoughness: 0.03, envMapIntensity: 1 })
  accentPaint.name = 'accent'
  bodyMaterial = paint
  src.traverse((o: Object3D) => {
    const mesh = o as Mesh
    if (!mesh.isMesh) return
    mesh.castShadow = SHADOW_CASTERS.has(mesh.name)
    const material = (Array.isArray(mesh.material) ? mesh.material[0] : mesh.material) as MeshStandardMaterial
    if (!material) return
    // Finish the neutral Blender materials roughly as the reference does.
    switch (material.name) {
      case 'carbon':
        material.color.setHex(0x343842)
        material.metalness = 0.12
        material.roughness = 0.46
        break
      case 'tyre':
        material.color.setHex(0x111114)
        material.metalness = 0.03
        material.roughness = 0.9
        break
      case 'glass':
        material.color.setHex(0x10141a)
        material.metalness = 0.92
        material.roughness = 0.08
        break
      case 'body':
        mesh.material = paint
        break
      case 'accent':
        accentPaint.color.copy(material.color)
        mesh.material = accentPaint
        break
      case 'glow':
        glowMaterial = material
        material.color.setHex(0x120602)
        material.emissive.setHex(0xff6a12)
        material.emissiveIntensity = 0
        material.toneMapped = false
        break
      case 'rainlight':
        material.color.setHex(0x240303)
        material.emissive.setHex(0xff2618)
        material.emissiveIntensity = 3.0
        material.toneMapped = false
        break
      default:
        break
    }
  })

  const brakeGlows = ['brake_glow_l', 'brake_glow_r'].map((n) => src.getObjectByName(n)).filter(Boolean) as Object3D[]
  const rainLight = (src.getObjectByName('rain_light') as Object3D) ?? null
  return { root, body, wheelObjects, bodyMaterial, brakeGlows, rainLight, glowMaterial }
}

export const Chassis = forwardRef<Group, PropsWithChildren<unknown>>(({ children }, ref) => {
  const crashAudio = useRef<PositionalAudioImpl>(null!)
  const wheels = useStore((s) => s.wheels)
  // The glb is not Draco-compressed, but drei's default is to fetch a decoder
  // from a Google CDN "just in case" — point it at the vendored one instead:
  // this game makes no third-party network requests.
  const { scene } = useGLTF(asset('models/f1car-2026.glb'), DRACO_PATH)
  const parts = useMemo(() => prepare(scene as Group), [scene])

  // Hand the wheel objects to the store refs so effects (dust, skid marks)
  // and Vehicle.tsx's spin/steer writes can reach them.
  useEffect(() => {
    parts.wheelObjects.forEach((o, i) => {
      const ref = wheels[i] as { current: Object3D | null }
      ref.current = o
    })
    return () => wheels.forEach((w) => ((w as { current: Object3D | null }).current = null))
  }, [parts, wheels])

  useFrame((state) => {
    const player = getPlayer()
    const { controls, color, sound } = getState()

    // Visual body attitude — dive under braking, squat under power, roll into
    // corners — plus a light speed vibration. Only the body: the wheels stay
    // on the road.
    const speedFactor = Math.min(1, player.speed / 90)
    parts.body.rotation.x = player.pitch + (Math.sin(state.clock.elapsedTime * 19) * speedFactor) / 240
    parts.body.rotation.z = player.roll + (Math.cos(state.clock.elapsedTime * 23) * speedFactor) / 260

    // Brake glow + rain light (the rain light doubles as the harvest light).
    const braking = controls.backward && player.v > 2
    for (const glow of parts.brakeGlows) glow.visible = braking
    if (parts.glowMaterial) parts.glowMaterial.emissiveIntensity = braking ? 2.4 : 0
    if (parts.rainLight) parts.rainLight.visible = braking || (controls.boost && mutation.boost > 0)

    if (parts.bodyMaterial) parts.bodyMaterial.color.lerp(c.set(color), 0.1)

    // Crash audio from the analytic wall response.
    if (mutation.wallHit > 0 && sound && crashAudio.current) {
      crashAudio.current.setVolume(Math.min(1, 0.3 + mutation.wallHit))
      if (!crashAudio.current.isPlaying) crashAudio.current.play()
      mutation.wallHit = 0
    }
  })

  return (
    <group ref={ref} dispose={null}>
      <primitive object={parts.body} />
      {parts.wheelObjects.map((o, i) => (
        <primitive key={i} object={o} />
      ))}
      {children}
      <PositionalAudio ref={crashAudio} url={asset('sounds/crash.mp3')} loop={false} distance={5} />
    </group>
  )
})
